### ISSUE TITLE
Press only publishes changed files [Priority 3]

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-press#265]
## Description ##
Press should only publish content files (collxml, index.cnxml, images) that have been edited. 

This is priority 3 for the Only Publish Changed Content epic. 

## Acceptance Criteria ##
After receiving only changed content from neb, using `neb publish` should only publish the modules that were changed.

## Test Plan ##

1. **Using Neb**, get the latest published collection.
2. In your computer, enable viewing hidden files and folders (On OSX: `Command` + `Shift` + `.`)
3. Delete all of the `.sha1sum` hidden files in the collection's folder.
4. Edit any some of the modules with valid content.
5. Publish the collection.
6. Expect to see output in the terminal coming from Press that shows that only the files you edited were published. 
_NOTE/TODO: This information is in the cryptic-looking output that neb generates on publish, so QA person might need a dev's help to decipher it._

**Comment by BryanEliDimas** [comment]
Changed the title and purpose of PR #292 which was intended to address this issue because we discovered a corner case that prevented us from making it work and reverted the changes until further notice. Now such PR actually enforces a rule that had only been communicated verbally to the content team: do not make any changes to `collection.xml` files.

**Comment by Bkblodget** [comment]
moved from priority 2 to priority 3

**Comment by omehes** [comment]
verified on neb 9.0.1 on various collections, col12012, col25479, etc
looks good
